@startmindmap
* настройка редактора (по вопросам)
** оценка
*** вид оценки
**** эмодзи ( да/нет)
**** оценка ( от 1 до 10)
** вопрос
*** Наименование вопроса
*** Вид ответа
**** Ввод ответа
**** Одновариантный выбор
**** Многовариантный выбор
@endmindmap